# Shown as the Sponsor button on the repository once GitHub Sponsors is enabled for the account.
github: noodlemctwoodle
custom: ["https://donate.stripe.com/3cI28sesu6T0f4n7IP2Nq00", "https://donate.stripe.com/8x2bJ23NQcdke0j3sz2Nq01"]
